### PR TITLE
Firefox without extension

### PR DESCRIPTION
**Pull request by Oliv4945**
As asked in #69 .
I only updated French translation, all other are required.

### CODE REVIEW

**Comment by Oliv4945** [comment]
Ok, I will rebase it tomorrow. 
Is there any documentation on Transiflex management ? Should I revert PHP files too ?

**Comment by ChristophWurst** [comment]
> Ok, I will rebase it tomorrow.

Take your time :wink: 

> Is there any documentation on Transiflex management ?

https://docs.nextcloud.com/server/13/developer_manual/core/translation.html



> Should I revert PHP files too ?

Only those changes in the `l10n` folder. The others should be fine.

Thanks!

**Comment by Oliv4945** [comment]
Done, I also remove PHP changes to avoid any mess with Transiflex.
I will change that later

**Comment by ChristophWurst** [comment]
Cherry-picked your readme fixes as https://github.com/nextcloud/twofactor_u2f/commit/5723bd3455adfd2867841c679fc97a586a5fa892. Thanks a lot!

**Pull request closed without merging**
