### PR TITLE
Support PHP 7.3

### PR DESCRIPTION
**Pull request by xf-**
Works for me.
No clue which task should run in matrix in PHP 7.3. PHP 7.0 support ends on according to Wikipedia 3 December. https://en.wikipedia.org/wiki/PHP

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Thanks!

- [ ] CI fails https://travis-ci.org/nextcloud/twofactor_u2f/jobs/455794009#L1739
- [ ] Requires a Nextcloud server with php7.3 support

**Comment by xf-** [comment]
done

**Comment by ChristophWurst** [comment]
I will test this as soon as I get access to php7.3. According to my colleagues there are a few issues with the new php version, so I'm hesitant releasing software I couldn't verify to work properly.

Thanks for fixing this!

> First-time contributor

Congrats :v:

**Comment by xf-** [comment]
one issue in server was filter_var constants for email changed.The debian php Maintainer has a repo with all available versions. https://deb.sury.org/

**Comment by ChristophWurst** [comment]
Thank you :v:

**Pull request merged**
