### PR TITLE
Release 1.5.2 (Backport for Nextcloud 13)

### PR DESCRIPTION
**Pull request by ChristophWurst**
TODO
- [x] Update changelog
- [x] Wait for positive testing feedback from the community
- [ ] Forward-port changelog once this has been merged and released

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Hey @tsenger, @gergelypolonkai and @algoterranean,

this should finally fix #96 for Nextcloud 13 (the other fixes only apply for master and thus Nextcloud 14). You can find a beta-release here: [twofactor_u2f.tar.gz](https://github.com/nextcloud/twofactor_u2f/files/1847146/twofactor_u2f.tar.gz). Please make a backup of your Nextcloud instance and replace the `apps/twofactor_u2f` folder with the content of this archive and let me know if this release fixes the problem for you. Thanks in advance!

**Comment by ChristophWurst** [comment]
FYI I've set the target release date to March 28th to give everyone time to test. If that's too short on notice, I'll postpone the release to next week.

**Comment by ChristophWurst** [comment]
@icewind1991 once again, would be great if you could test this on your phone. I really should get one those nfc keys …

**Comment by tsenger** [comment]
Just tested it on Android phone with mobile Chrome, Google Authenticator, Nextcloud 13 and a NFC-enabled U2F smartcard. 
Worked! Thanks @ChristophWurst !

**Comment by ChristophWurst** [comment]
Resolved a conflict, now let's see if CI is happy and then I'll merge this. @gergelypolonkai and @algoterranean please let me know if you encounter any issues. Otherwise I'll release this tomorrow morning.

**Comment by ChristophWurst** [comment]
The RC can be found at https://github.com/nextcloud/twofactor_u2f/releases/tag/1.5.2-RC1

**Comment by ChristophWurst** [comment]
I'm using FF Quantum and it works fine. Please file a new ticket if you still face problems. Thanks for your feedback!

**Comment by gergelypolonkai** [comment]
I don’t see this version on apps.nextcloud.com; the latest is 1.5.1

**Comment by ChristophWurst** [comment]
> I don’t see this version on apps.nextcloud.com; the latest is 1.5.1

That looks like a bug in the app store. Would you mind reporting it in their repo?

There's also one we discovered in the server last week. I'm working [on a fix right now](https://github.com/nextcloud/server/pull/9024). Please install the app manually this time. Sorry for the inconveniences.

**Pull request merged**
