### PR TITLE
Show warning if u2f is used via HTTP

### PR DESCRIPTION
**Pull request by ChristophWurst**
Simple approach to have a nicer UX in case the browser unexpectedly denies to authenticate U2F because HTTP is used. Working might not be perfect, but I didn't want to make it too technical.

cc @Nibbels 

Fixes https://github.com/nextcloud/twofactor_u2f/issues/21

### CODE REVIEW

**Comment by Nibbels** [comment]
I would be available to test this branch in general, but I dont have a nextcloud installation which is able to run without HTTPS.
Only If I temper with my headers and other settings again.

**Comment by ChristophWurst** [comment]
No worries. Do you run Linux on your notebook/PC? Then you could also set up a quick testing environment, that's easy. I could show you how to do that 😉

**Comment by Nibbels** [comment]
Hello again.

Well, I have one Raspberry PI for the 3D-Printer.
It runs some Webserver (Repetier-Server) already, but this one is not ment to server anything other than its own UI.

Greetings

**Comment by ChristophWurst** [comment]
Updated the branch to resolve a conflict. Please review so that I can publish a new release soon. Thanks!

**Pull request merged**
