### PR TITLE
update u2f-api

### PR DESCRIPTION
**Pull request by icewind1991**
The updated library is needed to support nfc tokens with android chrome

@LukasReschke do you have a nfc capable token? it's also supposed to work on iOS some way.

cc @ChristophWurst

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Cool, where did you find that?

**Comment by icewind1991** [comment]
It's from https://demo.yubico.com/js/u2f-api.js, which is what yubikey links to from their docs

**Comment by icewind1991** [comment]
It's from https://demo.yubico.com/js/u2f-api.js, which yubikey links to from their site

**Comment by icewind1991** [comment]
@ChristophWurst *poke*

This is preventing me from logging in from my android

**Pull request merged**
